import { Providers } from '@/components/Providers'
import './globals.css'
import { Open_Sans, Space_Grotesk } from 'next/font/google'

const open_sans = Open_Sans({ subsets: ['latin'], variable: '--font-open' })
const space_grotesk = Space_Grotesk({ subsets: ['latin'], variable: '--font-space' })

export const metadata = {
  title: 'Portifolio - Gabriel Rodrigues',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${space_grotesk.variable} ${open_sans.variable} font-sans`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
